// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDllw8KKhh__FTBsOt0HL_zbqSsDtKzi5Q',
    appId: '1:292779882647:web:c14a444e9ac1ae51ac91d2',
    messagingSenderId: '292779882647',
    projectId: 'astrachat-73307',
    authDomain: 'astrachat-73307.firebaseapp.com',
    storageBucket: 'astrachat-73307.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZx260kvJ0lxY_FTIAF8LCGcHNhyKfS6s',
    appId: '1:292779882647:android:63a14ea8cf77645eac91d2',
    messagingSenderId: '292779882647',
    projectId: 'astrachat-73307',
    storageBucket: 'astrachat-73307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQWxsZpTtPyypnh-DpPCM3R7Iy65-88E',
    appId: '1:292779882647:ios:8fd5c7e7fb4e8ad7ac91d2',
    messagingSenderId: '292779882647',
    projectId: 'astrachat-73307',
    storageBucket: 'astrachat-73307.appspot.com',
    iosBundleId: 'com.example.chatWithFirebase',
  );
}
